apiVersion: v1
kind: Service
metadata:
  name: pyroscope-ingester-headless
  namespace: pyroscope
  labels:
    app.kubernetes.io/name: pyroscope
    app.kubernetes.io/component: ingester
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: http
      port: 4040
      targetPort: http
    - name: memberlist
      port: 7946
      targetPort: memberlist
  selector:
    app.kubernetes.io/name: pyroscope
    app.kubernetes.io/component: ingester
