apiVersion: v1
kind: Service
metadata:
  name: pyroscope-query-frontend
  namespace: pyroscope
  labels:
    app.kubernetes.io/name: pyroscope
    app.kubernetes.io/component: query-frontend
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 4040
      targetPort: http
  selector:
    app.kubernetes.io/name: pyroscope
    app.kubernetes.io/component: query-frontend
