#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")/.."

declare -A DEFAULTS=(
  [POSTGRES_PORT]=15433
  [AIRFLOW_PORT]=18081
  [MLFLOW_PORT]=15000
  [API_PORT]=18000
  [WEB_PORT]=18500
  [MINIO_PORT]=19000
  [MINIO_CONSOLE_PORT]=19001
  [OLLAMA_PORT]=11434
)

is_free() {
  local p="$1"
  if command -v ss >/dev/null 2>&1; then
    ! ss -ltn "sport = :$p" 2>/dev/null | tail -n +2 | grep -q ":$p"
  elif command -v lsof >/dev/null 2>&1; then
    ! lsof -iTCP:"$p" -sTCP:LISTEN >/dev/null 2>&1
  else
    (echo >/dev/tcp/127.0.0.1/"$p") >/dev/null 2>&1 && return 1 || return 0
  fi
}
pick() { local p="$1"; while ! is_free "$p"; do p=$((p+1)); done; echo "$p"; }

PREV=""
[[ -f .env ]] && PREV=$(cat .env)
> .env
echo "# auto-generated by scripts/up.sh on $(date -Iseconds)" >> .env
for name in "${!DEFAULTS[@]}"; do
  want="${DEFAULTS[$name]}"
  got=$(pick "$want")
  [[ "$got" != "$want" ]] && echo "  [port] $name: $want busy -> $got"
  echo "$name=$got" >> .env
done
for key in LLM_PROVIDER OLLAMA_MODEL ANTHROPIC_API_KEY ANTHROPIC_MODEL \
           OPENAI_API_KEY OPENAI_MODEL GOOGLE_API_KEY GEMINI_MODEL PYROSCOPE_URL; do
  val=$(printf '%s\n' "$PREV" | grep -E "^${key}=" | head -1 || true)
  [[ -n "$val" ]] && echo "$val" >> .env
done

if ! curl -sf http://localhost:4041/ready >/dev/null 2>&1; then
  echo "  [warn] phase 1 Pyroscope not reachable on :4041"
  echo "  [warn] start phase 1 first: (cd .. && ./scripts/up.sh)"
fi
echo
grep -v '^#' .env
echo

docker compose up -d --build
source .env
cat <<EOF

====================================================================
Phase 2 stack starting.

  Web UI:     http://localhost:${WEB_PORT}
  API docs:   http://localhost:${API_PORT}/docs
  Airflow:    http://localhost:${AIRFLOW_PORT}   admin/admin
  MLflow:     http://localhost:${MLFLOW_PORT}
  MinIO:      http://localhost:${MINIO_CONSOLE_PORT}  minioadmin/minioadmin
  Postgres:   localhost:${POSTGRES_PORT}   postgres/postgres  (dbs: ai, airflow, mlflow)
  Ollama:     http://localhost:${OLLAMA_PORT}

Start synthetic traffic patterns against phase 1:
  docker compose --profile simulate up -d simulator

Seed initial data:
  ./scripts/seed.sh
====================================================================
EOF
