#!/usr/bin/env bash
# Launch the local demo stack. Auto-detects port conflicts and reassigns to
# the next free port above the default. Writes the final port map to .env.
set -euo pipefail
cd "$(dirname "$0")/.."

# name:default pairs
declare -A DEFAULTS=(
  [GRAFANA_PORT]=3001
  [PYROSCOPE_PORT]=4041
  [PROMETHEUS_PORT]=9091
  [DEMO_JVM11_PORT]=18080
  [DEMO_JVM21_PORT]=18081
  [REDIS_PORT]=16379
  [POSTGRES_PORT]=15432
  [MONGO_PORT]=17017
  [COUCHBASE_PORT]=18091
  [KAFKA_PORT]=19092
  [VAULT_PORT]=18200
)

is_free() {
  local p="$1"
  if command -v ss >/dev/null 2>&1; then
    ! ss -ltn "sport = :$p" 2>/dev/null | tail -n +2 | grep -q ":$p"
  elif command -v lsof >/dev/null 2>&1; then
    ! lsof -iTCP:"$p" -sTCP:LISTEN >/dev/null 2>&1
  else
    (echo >/dev/tcp/127.0.0.1/"$p") >/dev/null 2>&1 && return 1 || return 0
  fi
}

pick_port() {
  local want="$1" p="$want"
  while ! is_free "$p"; do p=$((p + 1)); done
  echo "$p"
}

> .env
echo "# auto-generated by scripts/up.sh on $(date -Iseconds)" >> .env
for name in "${!DEFAULTS[@]}"; do
  want="${DEFAULTS[$name]}"
  got=$(pick_port "$want")
  if [[ "$got" != "$want" ]]; then
    echo "  [port] $name: $want busy -> $got"
  fi
  echo "$name=$got" >> .env
done

echo
echo "Effective ports written to .env:"
sort .env | grep -v '^#'
echo

docker compose up -d --build

echo
source .env
cat <<EOF
====================================================================
Stack is starting. First-run build can take a few minutes.

  Grafana:     http://localhost:${GRAFANA_PORT}   (admin/admin)
  Pyroscope:   http://localhost:${PYROSCOPE_PORT}
  Prometheus:  http://localhost:${PROMETHEUS_PORT}
  JVM 11 app:  http://localhost:${DEMO_JVM11_PORT}/functions
  JVM 21 app:  http://localhost:${DEMO_JVM21_PORT}/functions

Run constant traffic:
  scripts/load.sh              # curl-based
  docker compose --profile load up k6   # k6 for 5m
====================================================================
EOF
