apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pyroscope.fullname" . }}-config
  labels:
    {{- include "pyroscope.labels" . | nindent 4 }}
data:
  config.yaml: |
    server:
      http_listen_port: 4040

    storage:
      backend: filesystem
      filesystem:
        {{- if eq .Values.mode "microservices" }}
        dir: /data/pyroscope
        {{- else }}
        dir: /data
        {{- end }}

    {{- if eq .Values.mode "microservices" }}
    memberlist:
      join_members:
        - {{ include "pyroscope.memberlistJoinAddress" . }}
    {{- end }}

    self_profiling:
      disable_push: true
