pyroscope.server.address=http://pyroscope:4040
pyroscope.format=jfr
pyroscope.profiler.event=itimer
pyroscope.profiler.interval=10ms
pyroscope.profiler.wall=20ms
pyroscope.profiler.alloc=256k
pyroscope.profiler.lock=10ms
pyroscope.upload.interval=15s
pyroscope.profiler.include=vert.x-eventloop-*|vert.x-worker-*|vert.x-internal-blocking-*|demo-*
pyroscope.labels=env=local-demo
pyroscope.log.level=warn
