#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
ENV_FILE="$PROJECT_DIR/.env"

# ---------------------------------------------------------------------------
# Port configuration: default ports for each service
# ---------------------------------------------------------------------------
declare -A PORTS=(
  [PYROSCOPE_PORT]=4040
  [PROMETHEUS_PORT]=9090
  [GRAFANA_PORT]=3000
  [API_GATEWAY_PORT]=8080
  [ORDER_SERVICE_PORT]=8081
  [PAYMENT_SERVICE_PORT]=8082
  [FRAUD_SERVICE_PORT]=8083
  [ACCOUNT_SERVICE_PORT]=8084
  [LOAN_SERVICE_PORT]=8085
  [NOTIFICATION_SERVICE_PORT]=8086
)

declare -A PORT_LABELS=(
  [PYROSCOPE_PORT]="Pyroscope"
  [PROMETHEUS_PORT]="Prometheus"
  [GRAFANA_PORT]="Grafana"
  [API_GATEWAY_PORT]="API Gateway"
  [ORDER_SERVICE_PORT]="Order Service"
  [PAYMENT_SERVICE_PORT]="Payment Service"
  [FRAUD_SERVICE_PORT]="Fraud Service"
  [ACCOUNT_SERVICE_PORT]="Account Service"
  [LOAN_SERVICE_PORT]="Loan Service"
  [NOTIFICATION_SERVICE_PORT]="Notification Service"
)

# ---------------------------------------------------------------------------
# Check if a port is available
# ---------------------------------------------------------------------------
port_free() {
  local port="$1"
  if command -v lsof > /dev/null 2>&1; then
    ! lsof -iTCP:"$port" -sTCP:LISTEN -P -n > /dev/null 2>&1
  elif command -v ss > /dev/null 2>&1; then
    ! ss -tlnp 2>/dev/null | grep -q ":${port} "
  elif command -v netstat > /dev/null 2>&1; then
    ! netstat -tlnp 2>/dev/null | grep -q ":${port} "
  else
    # Can't check — assume free
    return 0
  fi
}

# ---------------------------------------------------------------------------
# Find the next free port starting from a given port
# ---------------------------------------------------------------------------
find_free_port() {
  local port="$1"
  local max=$((port + 100))
  while [ "$port" -lt "$max" ]; do
    if port_free "$port"; then
      echo "$port"
      return 0
    fi
    ((port++))
  done
  echo ""
  return 1
}

# ---------------------------------------------------------------------------
# Check all ports and auto-resolve conflicts
# ---------------------------------------------------------------------------
echo "==> Checking port availability..."

CONFLICTS=0
RESOLVED_PORTS=()

for key in PYROSCOPE_PORT PROMETHEUS_PORT GRAFANA_PORT API_GATEWAY_PORT ORDER_SERVICE_PORT PAYMENT_SERVICE_PORT FRAUD_SERVICE_PORT ACCOUNT_SERVICE_PORT LOAN_SERVICE_PORT NOTIFICATION_SERVICE_PORT; do
  default=${PORTS[$key]}
  label=${PORT_LABELS[$key]}

  if port_free "$default"; then
    printf "    %-25s :%s  ✓ available\n" "$label" "$default"
    RESOLVED_PORTS+=("${key}=${default}")
  else
    free=$(find_free_port $((default + 1)))
    if [ -n "$free" ]; then
      printf "    %-25s :%s  ✗ in use → remapped to :%s\n" "$label" "$default" "$free"
      RESOLVED_PORTS+=("${key}=${free}")
      ((CONFLICTS++)) || true
    else
      echo "    ERROR: Could not find a free port near $default for $label"
      exit 1
    fi
  fi
done

# Write .env file for docker compose
echo "# Auto-generated by deploy.sh — port assignments" > "$ENV_FILE"
for entry in "${RESOLVED_PORTS[@]}"; do
  echo "$entry" >> "$ENV_FILE"
done

if [ "$CONFLICTS" -gt 0 ]; then
  echo ""
  echo "    Resolved $CONFLICTS port conflict(s). Ports saved to .env"
fi

echo ""

# ---------------------------------------------------------------------------
# Build and start
# ---------------------------------------------------------------------------
echo "==> Building and starting all services..."
cd "$PROJECT_DIR"
docker compose build --parallel
docker compose up -d

echo ""
echo "==> Waiting for services to become healthy..."
for svc in pyroscope prometheus grafana api-gateway order-service payment-service fraud-service account-service loan-service notification-service; do
  printf "    %-25s" "$svc"
  for i in $(seq 1 30); do
    if docker compose ps "$svc" 2>/dev/null | grep -q "Up"; then
      echo "UP"
      break
    fi
    sleep 2
    if [ "$i" -eq 30 ]; then
      echo "TIMEOUT – check logs with: docker compose logs $svc"
    fi
  done
done

# ---------------------------------------------------------------------------
# Print URLs using actual assigned ports
# ---------------------------------------------------------------------------
# Source the .env to get actual ports
set -a; source "$ENV_FILE"; set +a

echo ""
echo "==> Bank Enterprise Services:"
echo "    Grafana:        http://localhost:${GRAFANA_PORT}  (admin/admin)"
echo "    Pyroscope:      http://localhost:${PYROSCOPE_PORT}"
echo "    Prometheus:     http://localhost:${PROMETHEUS_PORT}"
echo "    API Gateway:    http://localhost:${API_GATEWAY_PORT}"
echo "    Order Service:  http://localhost:${ORDER_SERVICE_PORT}"
echo "    Payment Svc:    http://localhost:${PAYMENT_SERVICE_PORT}"
echo "    Fraud Svc:      http://localhost:${FRAUD_SERVICE_PORT}"
echo "    Account Svc:    http://localhost:${ACCOUNT_SERVICE_PORT}"
echo "    Loan Svc:       http://localhost:${LOAN_SERVICE_PORT}"
echo "    Notification:   http://localhost:${NOTIFICATION_SERVICE_PORT}"
echo ""
echo "==> Generate load with:  bash scripts/generate-load.sh"
