#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
ENV_FILE="$PROJECT_DIR/.env"

# ---------------------------------------------------------------------------
# Port configuration (bash 3.2 compatible — no associative arrays)
# ---------------------------------------------------------------------------
PORT_KEYS="PYROSCOPE_PORT PROMETHEUS_PORT GRAFANA_PORT API_GATEWAY_PORT ORDER_SERVICE_PORT PAYMENT_SERVICE_PORT FRAUD_SERVICE_PORT ACCOUNT_SERVICE_PORT LOAN_SERVICE_PORT NOTIFICATION_SERVICE_PORT"
PORT_DEFAULTS="4040 9090 3000 8080 8081 8082 8083 8084 8085 8086"
PORT_LABELS="Pyroscope Prometheus Grafana API_Gateway Order_Service Payment_Service Fraud_Service Account_Service Loan_Service Notification_Service"

# ---------------------------------------------------------------------------
# Check if a port is available
# ---------------------------------------------------------------------------
port_free() {
  local port="$1"
  if command -v lsof > /dev/null 2>&1; then
    ! lsof -iTCP:"$port" -sTCP:LISTEN -P -n > /dev/null 2>&1
  elif command -v ss > /dev/null 2>&1; then
    ! ss -tlnp 2>/dev/null | grep -q ":${port} "
  elif command -v netstat > /dev/null 2>&1; then
    ! netstat -tlnp 2>/dev/null | grep -q ":${port} "
  else
    return 0
  fi
}

# ---------------------------------------------------------------------------
# Find the next free port starting from a given port
# ---------------------------------------------------------------------------
find_free_port() {
  local port="$1"
  local max=$((port + 100))
  while [ "$port" -lt "$max" ]; do
    if port_free "$port"; then
      echo "$port"
      return 0
    fi
    port=$((port + 1))
  done
  echo ""
  return 1
}

# ---------------------------------------------------------------------------
# Check all ports and auto-resolve conflicts
# ---------------------------------------------------------------------------
echo "==> Checking port availability..."

CONFLICTS=0

# Convert space-delimited strings to arrays
set -f
keys=($PORT_KEYS)
defaults=($PORT_DEFAULTS)
labels=($PORT_LABELS)
set +f

# Write .env header
echo "# Auto-generated by deploy.sh — port assignments" > "$ENV_FILE"

i=0
for key in "${keys[@]}"; do
  default="${defaults[$i]}"
  label=$(echo "${labels[$i]}" | tr '_' ' ')

  if port_free "$default"; then
    printf "    %-25s :%s  available\n" "$label" "$default"
    echo "${key}=${default}" >> "$ENV_FILE"
  else
    free=$(find_free_port $((default + 1)))
    if [ -n "$free" ]; then
      printf "    %-25s :%s  in use -> remapped to :%s\n" "$label" "$default" "$free"
      echo "${key}=${free}" >> "$ENV_FILE"
      CONFLICTS=$((CONFLICTS + 1))
    else
      echo "    ERROR: Could not find a free port near $default for $label"
      exit 1
    fi
  fi
  i=$((i + 1))
done

if [ "$CONFLICTS" -gt 0 ]; then
  echo ""
  echo "    Resolved $CONFLICTS port conflict(s). Ports saved to .env"
fi

echo ""

# ---------------------------------------------------------------------------
# Build and start
# ---------------------------------------------------------------------------
echo "==> Building and starting all services..."
cd "$PROJECT_DIR"
docker compose build --parallel
docker compose up -d

echo ""
echo "==> Waiting for services to become healthy..."
for svc in pyroscope prometheus grafana api-gateway order-service payment-service fraud-service account-service loan-service notification-service; do
  printf "    %-25s" "$svc"
  for attempt in $(seq 1 30); do
    if docker compose ps "$svc" 2>/dev/null | grep -q "Up"; then
      echo "UP"
      break
    fi
    sleep 2
    if [ "$attempt" -eq 30 ]; then
      echo "TIMEOUT – check logs with: docker compose logs $svc"
    fi
  done
done

# ---------------------------------------------------------------------------
# Print URLs using actual assigned ports
# ---------------------------------------------------------------------------
set -a; source "$ENV_FILE"; set +a

echo ""
echo "==> Bank Enterprise Services:"
echo "    Grafana:        http://localhost:${GRAFANA_PORT}  (admin/admin)"
echo "    Pyroscope:      http://localhost:${PYROSCOPE_PORT}"
echo "    Prometheus:     http://localhost:${PROMETHEUS_PORT}"
echo "    API Gateway:    http://localhost:${API_GATEWAY_PORT}"
echo "    Order Service:  http://localhost:${ORDER_SERVICE_PORT}"
echo "    Payment Svc:    http://localhost:${PAYMENT_SERVICE_PORT}"
echo "    Fraud Svc:      http://localhost:${FRAUD_SERVICE_PORT}"
echo "    Account Svc:    http://localhost:${ACCOUNT_SERVICE_PORT}"
echo "    Loan Svc:       http://localhost:${LOAN_SERVICE_PORT}"
echo "    Notification:   http://localhost:${NOTIFICATION_SERVICE_PORT}"
echo ""
echo "==> Generate load with:  bash scripts/generate-load.sh"
