#!/usr/bin/env bash
# =============================================================================
# upload-to-confluence.sh — Upload converted docs to Confluence via REST API
#
# Uploads .confluence.txt files (generated by export-to-confluence.sh) to a
# Confluence instance as wiki markup pages. Tested with Confluence 9.2.3.
#
# Prerequisites:
#   1. Run export-to-confluence.sh first to generate .confluence.txt files
#   2. Set required environment variables (see below)
#
# Required environment variables:
#   CONFLUENCE_URL        Base URL of your Confluence instance
#                         Example: https://wiki.company.com
#   CONFLUENCE_SPACE_KEY  Confluence space key to create pages in
#                         Example: PYRO or DEVOPS
#   CONFLUENCE_USER       Confluence username (or email for Cloud)
#   CONFLUENCE_TOKEN      Personal access token (Server/DC) or API token (Cloud)
#                         Generate at: Profile → Personal Access Tokens (Server/DC)
#                         or https://id.atlassian.com/manage-profile/security/api-tokens (Cloud)
#
# Optional environment variables:
#   CONFLUENCE_PARENT_ID  Parent page ID to nest all pages under
#                         Find via: page URL → ?pageId=12345, or API
#                         Default: pages created at space root
#   CONFLUENCE_LABEL      Label to apply to all uploaded pages
#                         Default: pyroscope-docs
#   CONFLUENCE_PREFIX     Prefix for page titles to avoid collisions
#                         Default: "Pyroscope - "
#   CONFLUENCE_EXPORT_DIR Directory containing .confluence.txt files
#                         Default: ./confluence-export
#   CONFLUENCE_DRY_RUN    Set to "true" to validate without uploading
#                         Default: false
#   CONFLUENCE_VERIFY_SSL Set to "false" to skip TLS verification (self-signed certs)
#                         Default: true
#
# Usage:
#   # Upload all docs
#   export CONFLUENCE_URL=https://wiki.company.com
#   export CONFLUENCE_SPACE_KEY=PYRO
#   export CONFLUENCE_USER=john.doe
#   export CONFLUENCE_TOKEN=your-personal-access-token
#   bash scripts/upload-to-confluence.sh
#
#   # Upload a single file
#   bash scripts/upload-to-confluence.sh tls-setup.confluence.txt
#
#   # Dry run (validate only, no uploads)
#   CONFLUENCE_DRY_RUN=true bash scripts/upload-to-confluence.sh
#
#   # Upload under a parent page
#   CONFLUENCE_PARENT_ID=12345678 bash scripts/upload-to-confluence.sh
#
#   # Use .env file
#   source .env.confluence && bash scripts/upload-to-confluence.sh
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

# --- Parse arguments first (--help doesn't need env vars) ---
SINGLE_FILE=""
ARGS_LIST=false
ARGS_DRY_RUN=false

for arg in "$@"; do
    case "$arg" in
        --help|-h)
            sed -n '/^# Usage:/,/^# ====/p' "$0" | grep '^#' | sed 's/^# \?//'
            exit 0 ;;
        --list)    ARGS_LIST=true ;;
        --dry-run) ARGS_DRY_RUN=true ;;
    esac
done

# --- Required env vars ---
: "${CONFLUENCE_URL:?Set CONFLUENCE_URL (e.g. https://wiki.company.com)}"
: "${CONFLUENCE_SPACE_KEY:?Set CONFLUENCE_SPACE_KEY (e.g. PYRO)}"
: "${CONFLUENCE_USER:?Set CONFLUENCE_USER (e.g. john.doe)}"
: "${CONFLUENCE_TOKEN:?Set CONFLUENCE_TOKEN (personal access token)}"

# --- Optional env vars ---
CONFLUENCE_PARENT_ID="${CONFLUENCE_PARENT_ID:-}"
CONFLUENCE_LABEL="${CONFLUENCE_LABEL:-pyroscope-docs}"
CONFLUENCE_PREFIX="${CONFLUENCE_PREFIX:-Pyroscope - }"
CONFLUENCE_DRY_RUN="${CONFLUENCE_DRY_RUN:-false}"
CONFLUENCE_VERIFY_SSL="${CONFLUENCE_VERIFY_SSL:-true}"

if [[ "$ARGS_DRY_RUN" == "true" ]]; then
    CONFLUENCE_DRY_RUN=true
fi

EXPORT_DIR="${CONFLUENCE_EXPORT_DIR:-${REPO_ROOT}/confluence-export}"
CURL_OPTS=(-s -f)

if [[ "$CONFLUENCE_VERIFY_SSL" == "false" ]]; then
    CURL_OPTS+=(-k)
fi

# Strip trailing slash from URL
CONFLUENCE_URL="${CONFLUENCE_URL%/}"

# Confluence Server/DC REST API base
API_BASE="${CONFLUENCE_URL}/rest/api/content"

# --- Parse remaining arguments ---
if [[ "$ARGS_LIST" == "true" ]]; then
    echo "Files available for upload in: ${EXPORT_DIR}"
    echo ""
    find "${EXPORT_DIR}" -name '*.confluence.txt' -type f | sort | while read -r f; do
        echo "  $(basename "$f")"
    done
    exit 0
fi

for arg in "$@"; do
    case "$arg" in
        --help|-h|--dry-run|--list) continue ;;
        *)
            if [[ -f "$arg" ]]; then
                SINGLE_FILE="$arg"
            elif [[ -f "${EXPORT_DIR}/$arg" ]]; then
                SINGLE_FILE="${EXPORT_DIR}/$arg"
            else
                echo "Error: File not found: $arg" >&2
                exit 1
            fi
            ;;
    esac
done

# --- Validate prerequisites ---
if [[ ! -d "$EXPORT_DIR" ]]; then
    echo "Error: Export directory not found: ${EXPORT_DIR}" >&2
    echo "Run 'bash scripts/export-to-confluence.sh' first to generate Confluence markup files." >&2
    exit 1
fi

if ! command -v curl &>/dev/null; then
    echo "Error: curl is required but not found." >&2
    exit 1
fi

if ! command -v jq &>/dev/null; then
    echo "Warning: jq not found. Response parsing will be limited." >&2
    HAS_JQ=false
else
    HAS_JQ=true
fi

# --- Test connectivity ---
echo "Confluence instance: ${CONFLUENCE_URL}"
echo "Space:              ${CONFLUENCE_SPACE_KEY}"
echo "User:               ${CONFLUENCE_USER}"
echo "Parent page ID:     ${CONFLUENCE_PARENT_ID:-<space root>}"
echo "Page prefix:        ${CONFLUENCE_PREFIX}"
echo "Label:              ${CONFLUENCE_LABEL}"
echo "Dry run:            ${CONFLUENCE_DRY_RUN}"
echo "TLS verification:   ${CONFLUENCE_VERIFY_SSL}"
echo ""

if [[ "$CONFLUENCE_DRY_RUN" != "true" ]]; then
    echo -n "Testing connection... "
    HTTP_CODE=$(curl "${CURL_OPTS[@]}" -o /dev/null -w "%{http_code}" \
        -u "${CONFLUENCE_USER}:${CONFLUENCE_TOKEN}" \
        "${API_BASE}?spaceKey=${CONFLUENCE_SPACE_KEY}&limit=1" 2>/dev/null) || true
    if [[ "$HTTP_CODE" == "200" ]]; then
        echo "OK (HTTP ${HTTP_CODE})"
    elif [[ "$HTTP_CODE" == "401" ]]; then
        echo "FAILED (HTTP 401 — bad credentials)"
        echo "Check CONFLUENCE_USER and CONFLUENCE_TOKEN." >&2
        exit 1
    elif [[ "$HTTP_CODE" == "403" ]]; then
        echo "FAILED (HTTP 403 — insufficient permissions)"
        echo "Ensure the user has 'Add Pages' permission in space ${CONFLUENCE_SPACE_KEY}." >&2
        exit 1
    elif [[ "$HTTP_CODE" == "404" ]]; then
        echo "FAILED (HTTP 404 — space not found or wrong URL)"
        echo "Check CONFLUENCE_URL and CONFLUENCE_SPACE_KEY." >&2
        exit 1
    else
        echo "FAILED (HTTP ${HTTP_CODE})"
        echo "Check CONFLUENCE_URL is reachable and correct." >&2
        exit 1
    fi
    echo ""
fi

# --- Escape JSON string (for wiki markup body) ---
json_escape() {
    # Read stdin, escape for JSON string value
    python3 -c "
import sys, json
content = sys.stdin.read()
print(json.dumps(content), end='')
" 2>/dev/null || {
        # Fallback if python3 not available: basic escaping
        sed 's/\\/\\\\/g; s/"/\\"/g; s/\t/\\t/g' | \
        awk '{printf "%s\\n", $0}' | sed 's/\\n$//'
    }
}

# --- Find existing page by title ---
find_page_id() {
    local title="$1"
    local encoded_title
    encoded_title=$(python3 -c "import urllib.parse; print(urllib.parse.quote('$title'))" 2>/dev/null || echo "$title")

    local response
    response=$(curl "${CURL_OPTS[@]}" \
        -u "${CONFLUENCE_USER}:${CONFLUENCE_TOKEN}" \
        "${API_BASE}?spaceKey=${CONFLUENCE_SPACE_KEY}&title=${encoded_title}&limit=1" 2>/dev/null) || return 1

    if [[ "$HAS_JQ" == "true" ]]; then
        echo "$response" | jq -r '.results[0].id // empty' 2>/dev/null
    else
        echo "$response" | grep -o '"id":"[0-9]*"' | head -1 | grep -o '[0-9]*'
    fi
}

# --- Get page version ---
get_page_version() {
    local page_id="$1"
    local response
    response=$(curl "${CURL_OPTS[@]}" \
        -u "${CONFLUENCE_USER}:${CONFLUENCE_TOKEN}" \
        "${API_BASE}/${page_id}" 2>/dev/null) || return 1

    if [[ "$HAS_JQ" == "true" ]]; then
        echo "$response" | jq -r '.version.number // "0"' 2>/dev/null
    else
        echo "$response" | grep -o '"number":[0-9]*' | head -1 | grep -o '[0-9]*'
    fi
}

# --- Upload or update a single page ---
upload_page() {
    local file="$1"
    local basename
    basename=$(basename "$file" .confluence.txt)

    # Derive title from filename
    local title="${CONFLUENCE_PREFIX}${basename}"
    # Clean up title: replace hyphens with spaces, collapse multiple spaces
    title=$(echo "$title" | sed 's/-/ /g; s/  */ /g')

    local wiki_body
    wiki_body=$(cat "$file" | json_escape)

    # Build JSON payload
    local ancestors=""
    if [[ -n "$CONFLUENCE_PARENT_ID" ]]; then
        ancestors='"ancestors": [{"id": "'"${CONFLUENCE_PARENT_ID}"'"}],'
    fi

    # Check if page already exists
    local existing_id
    existing_id=$(find_page_id "$title" 2>/dev/null) || true

    if [[ -n "$existing_id" ]]; then
        # Update existing page
        local version
        version=$(get_page_version "$existing_id" 2>/dev/null) || version=0
        local new_version=$((version + 1))

        if [[ "$CONFLUENCE_DRY_RUN" == "true" ]]; then
            echo "  [DRY RUN] Would UPDATE: ${title} (id=${existing_id}, v${version} → v${new_version})"
            return 0
        fi

        local payload
        payload=$(cat <<ENDJSON
{
    "id": "${existing_id}",
    "type": "page",
    "title": "${title}",
    "space": {"key": "${CONFLUENCE_SPACE_KEY}"},
    ${ancestors}
    "version": {"number": ${new_version}},
    "body": {
        "wiki": {
            "value": ${wiki_body},
            "representation": "wiki"
        }
    },
    "metadata": {
        "labels": [{"name": "${CONFLUENCE_LABEL}", "prefix": "global"}]
    }
}
ENDJSON
)
        local response
        response=$(curl "${CURL_OPTS[@]}" -w "\n%{http_code}" \
            -u "${CONFLUENCE_USER}:${CONFLUENCE_TOKEN}" \
            -X PUT \
            -H "Content-Type: application/json" \
            -d "$payload" \
            "${API_BASE}/${existing_id}" 2>/dev/null) || true

        local http_code
        http_code=$(echo "$response" | tail -1)
        if [[ "$http_code" == "200" ]]; then
            echo "  UPDATED: ${title} (id=${existing_id}, v${new_version})"
        else
            echo "  FAILED:  ${title} (HTTP ${http_code})" >&2
            if [[ "$HAS_JQ" == "true" ]]; then
                echo "$response" | head -1 | jq -r '.message // empty' 2>/dev/null | sed 's/^/           /' >&2
            fi
            return 1
        fi
    else
        # Create new page
        if [[ "$CONFLUENCE_DRY_RUN" == "true" ]]; then
            echo "  [DRY RUN] Would CREATE: ${title}"
            return 0
        fi

        local payload
        payload=$(cat <<ENDJSON
{
    "type": "page",
    "title": "${title}",
    "space": {"key": "${CONFLUENCE_SPACE_KEY}"},
    ${ancestors}
    "body": {
        "wiki": {
            "value": ${wiki_body},
            "representation": "wiki"
        }
    },
    "metadata": {
        "labels": [{"name": "${CONFLUENCE_LABEL}", "prefix": "global"}]
    }
}
ENDJSON
)
        local response
        response=$(curl "${CURL_OPTS[@]}" -w "\n%{http_code}" \
            -u "${CONFLUENCE_USER}:${CONFLUENCE_TOKEN}" \
            -X POST \
            -H "Content-Type: application/json" \
            -d "$payload" \
            "${API_BASE}" 2>/dev/null) || true

        local http_code
        http_code=$(echo "$response" | tail -1)
        if [[ "$http_code" == "200" ]]; then
            local page_id=""
            if [[ "$HAS_JQ" == "true" ]]; then
                page_id=$(echo "$response" | head -1 | jq -r '.id // empty' 2>/dev/null)
            fi
            echo "  CREATED: ${title}${page_id:+ (id=${page_id})}"
        else
            echo "  FAILED:  ${title} (HTTP ${http_code})" >&2
            if [[ "$HAS_JQ" == "true" ]]; then
                echo "$response" | head -1 | jq -r '.message // empty' 2>/dev/null | sed 's/^/           /' >&2
            fi
            return 1
        fi
    fi
}

# --- Main ---
echo "Uploading to Confluence..."
echo ""

success=0
failed=0

if [[ -n "$SINGLE_FILE" ]]; then
    if upload_page "$SINGLE_FILE"; then
        success=$((success + 1))
    else
        failed=$((failed + 1))
    fi
else
    find "${EXPORT_DIR}" -name '*.confluence.txt' -type f | sort | while read -r f; do
        if upload_page "$f"; then
            success=$((success + 1))
        else
            failed=$((failed + 1))
        fi
    done
fi

echo ""
echo "Done. ${success} uploaded, ${failed} failed."

if [[ "$CONFLUENCE_DRY_RUN" == "true" ]]; then
    echo ""
    echo "This was a dry run. Set CONFLUENCE_DRY_RUN=false (or unset) to upload for real."
fi

echo ""
echo "Example .env.confluence file for convenience:"
echo ""
echo '  CONFLUENCE_URL=https://wiki.company.com'
echo '  CONFLUENCE_SPACE_KEY=PYRO'
echo '  CONFLUENCE_USER=john.doe'
echo '  CONFLUENCE_TOKEN=your-personal-access-token'
echo '  CONFLUENCE_PARENT_ID=12345678'
echo '  # CONFLUENCE_PREFIX="Pyroscope - "'
echo '  # CONFLUENCE_LABEL=pyroscope-docs'
echo '  # CONFLUENCE_VERIFY_SSL=false'
