#!/usr/bin/env bash
# =============================================================================
# upload-to-confluence.sh — Upload converted docs to Confluence via REST API
#
# Uploads .confluence.txt files (generated by export-to-confluence.sh) to a
# Confluence instance as wiki markup pages. Tested with Confluence 9.2.3.
#
# Authentication:
#   Confluence Server/DC (9.x): Personal Access Token (Bearer auth)
#   Confluence Cloud:           API token with basic auth (user:token)
#
# Prerequisites:
#   1. Run export-to-confluence.sh first to generate .confluence.txt files
#   2. Set required environment variables (see below)
#
# Required environment variables:
#   CONFLUENCE_URL        Base URL of your Confluence instance
#                         Example: https://wiki.company.com
#   CONFLUENCE_SPACE_KEY  Confluence space key to create pages in
#                         Example: PYRO or DEVOPS
#   CONFLUENCE_TOKEN      Personal access token (Server/DC) or API token (Cloud)
#                         Server/DC: Profile → Personal Access Tokens
#                         Cloud: https://id.atlassian.com/manage-profile/security/api-tokens
#
# Required for Cloud only:
#   CONFLUENCE_USER       Confluence email (only needed for Cloud basic auth)
#
# Optional environment variables:
#   CONFLUENCE_AUTH_TYPE  Authentication type: "pat" (default) or "basic"
#                         pat:   Bearer token auth (Confluence Server/DC 7.9+)
#                         basic: Basic auth with user:token (Confluence Cloud)
#   CONFLUENCE_PARENT_ID  Parent page ID to nest all pages under
#                         Find via: page URL → ?pageId=12345, or API
#                         Default: auto-creates "Pyroscope Documentation" page
#   CONFLUENCE_PARENT_TITLE  Title of auto-created parent page
#                         Default: "Pyroscope Documentation"
#   CONFLUENCE_LABEL      Label to apply to all uploaded pages
#                         Default: pyroscope-docs
#   CONFLUENCE_PREFIX     Prefix for page titles to avoid collisions
#                         Default: "Pyroscope - "
#   CONFLUENCE_EXPORT_DIR Directory containing .confluence.txt files
#                         Default: ./confluence-export
#   CONFLUENCE_DRY_RUN    Ignored — dry run is the default. Use --confirm to upload.
#   CONFLUENCE_VERIFY_SSL Set to "false" to skip TLS verification (self-signed certs)
#                         Default: true
#
# Workflow:
#   Step 1: Export docs to Confluence markup files
#     bash scripts/export-to-confluence.sh --enterprise
#
#   Step 2: Preview what would be uploaded (dry run — default behavior)
#     bash scripts/upload-to-confluence.sh --enterprise
#
#   Step 3: Actually upload (requires --confirm flag)
#     bash scripts/upload-to-confluence.sh --enterprise --confirm
#
# Usage:
#   # Set environment (or use .env file)
#   export CONFLUENCE_URL=https://wiki.company.com
#   export CONFLUENCE_SPACE_KEY=PYRO
#   export CONFLUENCE_TOKEN=your-personal-access-token
#
#   # Preview enterprise docs (dry run — no uploads)
#   bash scripts/upload-to-confluence.sh --enterprise
#
#   # Upload enterprise docs for real
#   bash scripts/upload-to-confluence.sh --enterprise --confirm
#
#   # Upload all exported docs (not just enterprise)
#   bash scripts/upload-to-confluence.sh --confirm
#
#   # Upload a single file
#   bash scripts/upload-to-confluence.sh tls-setup.confluence.txt --confirm
#
#   # Upload under an existing parent page (skip auto-create)
#   CONFLUENCE_PARENT_ID=12345678 bash scripts/upload-to-confluence.sh --enterprise --confirm
#
#   # Confluence Cloud (basic auth with email + API token)
#   CONFLUENCE_AUTH_TYPE=basic CONFLUENCE_USER=john.doe@company.com \
#     bash scripts/upload-to-confluence.sh --enterprise --confirm
#
#   # Use .env file
#   source .env.confluence && bash scripts/upload-to-confluence.sh --enterprise --confirm
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

# --- Auto-load .env.confluence if present (never committed — in .gitignore) ---
if [[ -f "${REPO_ROOT}/.env.confluence" ]]; then
    echo "Loading config from .env.confluence"
    source "${REPO_ROOT}/.env.confluence"
fi

# --- Parse arguments first (--help doesn't need env vars) ---
SINGLE_FILE=""
ARGS_LIST=false
ARGS_CONFIRM=false
ARGS_ENTERPRISE=false

for arg in "$@"; do
    case "$arg" in
        --help|-h)
            sed -n '/^# Usage:/,/^# ====/p' "$0" | grep '^#' | sed 's/^# \?//'
            exit 0 ;;
        --list)       ARGS_LIST=true ;;
        --confirm)    ARGS_CONFIRM=true ;;
        --enterprise) ARGS_ENTERPRISE=true ;;
    esac
done

# --- Required env vars ---
: "${CONFLUENCE_URL:?Set CONFLUENCE_URL (e.g. https://wiki.company.com)}"
: "${CONFLUENCE_SPACE_KEY:?Set CONFLUENCE_SPACE_KEY (e.g. PYRO)}"
: "${CONFLUENCE_TOKEN:?Set CONFLUENCE_TOKEN (personal access token)}"

# --- Auth type ---
CONFLUENCE_AUTH_TYPE="${CONFLUENCE_AUTH_TYPE:-pat}"

if [[ "$CONFLUENCE_AUTH_TYPE" == "basic" ]]; then
    : "${CONFLUENCE_USER:?Set CONFLUENCE_USER for basic auth (e.g. john.doe@company.com)}"
fi

# --- Optional env vars ---
CONFLUENCE_PARENT_ID="${CONFLUENCE_PARENT_ID:-}"
CONFLUENCE_PARENT_TITLE="${CONFLUENCE_PARENT_TITLE:-Pyroscope Documentation}"
CONFLUENCE_LABEL="${CONFLUENCE_LABEL:-pyroscope-docs}"
CONFLUENCE_PREFIX="${CONFLUENCE_PREFIX:-Pyroscope - }"
CONFLUENCE_VERIFY_SSL="${CONFLUENCE_VERIFY_SSL:-true}"

# Default to dry run — must pass --confirm to actually upload
if [[ "$ARGS_CONFIRM" == "true" ]]; then
    CONFLUENCE_DRY_RUN=false
else
    CONFLUENCE_DRY_RUN=true
fi

EXPORT_DIR="${CONFLUENCE_EXPORT_DIR:-${REPO_ROOT}/confluence-export}"
MANIFEST_FILE="${REPO_ROOT}/docs/confluence-manifest.txt"
CURL_OPTS=(-s)

if [[ "$CONFLUENCE_VERIFY_SSL" == "false" ]]; then
    CURL_OPTS+=(-k)
fi

# Strip trailing slash from URL
CONFLUENCE_URL="${CONFLUENCE_URL%/}"

# Confluence Server/DC REST API base
API_BASE="${CONFLUENCE_URL}/rest/api/content"

# --- Build auth header based on auth type ---
build_auth_args() {
    if [[ "$CONFLUENCE_AUTH_TYPE" == "pat" ]]; then
        # Confluence Server/DC 7.9+ Personal Access Token: Bearer auth
        echo "-H"
        echo "Authorization: Bearer ${CONFLUENCE_TOKEN}"
    else
        # Confluence Cloud: Basic auth with user:api-token
        echo "-u"
        echo "${CONFLUENCE_USER}:${CONFLUENCE_TOKEN}"
    fi
}

# Store auth args in an array for reuse
AUTH_ARGS=()
while IFS= read -r line; do
    AUTH_ARGS+=("$line")
done < <(build_auth_args)

# --- Parse remaining arguments ---
if [[ "$ARGS_LIST" == "true" ]]; then
    echo "Files available for upload in: ${EXPORT_DIR}"
    echo ""
    find "${EXPORT_DIR}" -name '*.confluence.txt' -type f | sort | while read -r f; do
        echo "  $(basename "$f")"
    done
    exit 0
fi

for arg in "$@"; do
    case "$arg" in
        --help|-h|--dry-run|--list|--enterprise|--confirm) continue ;;
        *)
            if [[ -f "$arg" ]]; then
                SINGLE_FILE="$arg"
            elif [[ -f "${EXPORT_DIR}/$arg" ]]; then
                SINGLE_FILE="${EXPORT_DIR}/$arg"
            else
                echo "Error: File not found: $arg" >&2
                exit 1
            fi
            ;;
    esac
done

# --- Validate prerequisites ---
if [[ ! -d "$EXPORT_DIR" ]]; then
    echo "Error: Export directory not found: ${EXPORT_DIR}" >&2
    echo "Run 'bash scripts/export-to-confluence.sh' first to generate Confluence markup files." >&2
    exit 1
fi

if ! command -v curl &>/dev/null; then
    echo "Error: curl is required but not found." >&2
    exit 1
fi

if ! command -v jq &>/dev/null; then
    echo "Warning: jq not found. Response parsing will be limited." >&2
    HAS_JQ=false
else
    HAS_JQ=true
fi

# --- Print configuration ---
echo "Confluence instance: ${CONFLUENCE_URL}"
echo "Space:              ${CONFLUENCE_SPACE_KEY}"
echo "Auth type:          ${CONFLUENCE_AUTH_TYPE}"
if [[ "$CONFLUENCE_AUTH_TYPE" == "basic" ]]; then
    echo "User:               ${CONFLUENCE_USER}"
fi
echo "Parent page ID:     ${CONFLUENCE_PARENT_ID:-<auto-create '${CONFLUENCE_PARENT_TITLE}'>}"
echo "Page prefix:        ${CONFLUENCE_PREFIX}"
echo "Label:              ${CONFLUENCE_LABEL}"
echo "Enterprise only:    ${ARGS_ENTERPRISE}"
echo "Dry run:            ${CONFLUENCE_DRY_RUN}"
echo "TLS verification:   ${CONFLUENCE_VERIFY_SSL}"
echo ""

# --- Test connectivity ---
if [[ "$CONFLUENCE_DRY_RUN" != "true" ]]; then
    echo -n "Testing connection... "
    HTTP_CODE=$(curl "${CURL_OPTS[@]}" "${AUTH_ARGS[@]}" -o /dev/null -w "%{http_code}" \
        "${API_BASE}?spaceKey=${CONFLUENCE_SPACE_KEY}&limit=1" 2>/dev/null) || true
    if [[ "$HTTP_CODE" == "200" ]]; then
        echo "OK (HTTP ${HTTP_CODE})"
    elif [[ "$HTTP_CODE" == "401" ]]; then
        echo "FAILED (HTTP 401 — bad credentials)"
        if [[ "$CONFLUENCE_AUTH_TYPE" == "pat" ]]; then
            echo "Check CONFLUENCE_TOKEN (Personal Access Token)." >&2
            echo "Generate at: ${CONFLUENCE_URL}/plugins/personalaccesstokens/usertokens.action" >&2
        else
            echo "Check CONFLUENCE_USER and CONFLUENCE_TOKEN." >&2
        fi
        exit 1
    elif [[ "$HTTP_CODE" == "403" ]]; then
        echo "FAILED (HTTP 403 — insufficient permissions)"
        echo "Ensure the token owner has 'Add Pages' permission in space ${CONFLUENCE_SPACE_KEY}." >&2
        exit 1
    elif [[ "$HTTP_CODE" == "404" ]]; then
        echo "FAILED (HTTP 404 — space not found or wrong URL)"
        echo "Check CONFLUENCE_URL and CONFLUENCE_SPACE_KEY." >&2
        exit 1
    else
        echo "FAILED (HTTP ${HTTP_CODE})"
        echo "Check CONFLUENCE_URL is reachable and correct." >&2
        exit 1
    fi
    echo ""
fi

# --- Escape JSON string (for wiki markup body) ---
json_escape() {
    python3 -c "
import sys, json
content = sys.stdin.read()
print(json.dumps(content), end='')
" 2>/dev/null || {
        sed 's/\\/\\\\/g; s/"/\\"/g; s/\t/\\t/g' | \
        awk '{printf "%s\\n", $0}' | sed 's/\\n$//'
    }
}

# --- Find existing page by title ---
find_page_id() {
    local title="$1"
    local encoded_title
    # Use python3 for proper URL encoding; fallback to sed-based encoding for spaces
    encoded_title=$(python3 -c "import urllib.parse, sys; print(urllib.parse.quote(sys.argv[1]))" "$title" 2>/dev/null \
        || echo "$title" | sed 's/ /%20/g; s/&/%26/g; s/+/%2B/g')

    local response
    response=$(curl "${CURL_OPTS[@]}" "${AUTH_ARGS[@]}" \
        "${API_BASE}?spaceKey=${CONFLUENCE_SPACE_KEY}&title=${encoded_title}&limit=1" 2>/dev/null) || return 1

    if [[ "$HAS_JQ" == "true" ]]; then
        echo "$response" | jq -r '.results[0].id // empty' 2>/dev/null
    else
        echo "$response" | grep -o '"id":"[0-9]*"' | head -1 | grep -o '[0-9]*'
    fi
}

# --- Get page version ---
get_page_version() {
    local page_id="$1"
    local response
    response=$(curl "${CURL_OPTS[@]}" "${AUTH_ARGS[@]}" \
        "${API_BASE}/${page_id}" 2>/dev/null) || return 1

    if [[ "$HAS_JQ" == "true" ]]; then
        echo "$response" | jq -r '.version.number // "0"' 2>/dev/null
    else
        echo "$response" | grep -o '"number":[0-9]*' | head -1 | grep -o '[0-9]*'
    fi
}

# --- Get space home page ID ---
get_space_home_page_id() {
    local response
    response=$(curl "${CURL_OPTS[@]}" "${AUTH_ARGS[@]}" \
        "${CONFLUENCE_URL}/rest/api/space/${CONFLUENCE_SPACE_KEY}?expand=homepage" 2>/dev/null) || return 1

    if [[ "$HAS_JQ" == "true" ]]; then
        echo "$response" | jq -r '.homepage.id // empty' 2>/dev/null
    else
        echo "$response" | grep -o '"homepage":{[^}]*"id":"[0-9]*"' | grep -o '[0-9]*' | head -1
    fi
}

# --- Build parent page index body from manifest ---
build_index_body() {
    local body="h1. Pyroscope Documentation\n\n"
    body+="Enterprise documentation for Pyroscope continuous profiling, organized by the [Diataxis framework|https://diataxis.fr/].\n\n"
    body+="----\n\n"

    local current_section=""

    if [[ ! -f "$MANIFEST_FILE" ]]; then
        # Fallback if manifest not available
        body+="{children:sort=title|excerpt=simple}"
        echo "$body"
        return
    fi

    while IFS= read -r line; do
        # Detect section headers (lines like "# --- Explanation ... ---")
        if [[ "$line" =~ ^#\ ---\ (.+)\ --- ]]; then
            section="${BASH_REMATCH[1]}"
            # Extract just the category name (before the parenthetical)
            section_name=$(echo "$section" | sed 's/ (.*//')
            case "$section_name" in
                Explanation)
                    body+="h2. Explanation (Understanding-Oriented)\n\n"
                    body+="Conceptual guides that explain how Pyroscope works and why.\n\n" ;;
                Tutorials)
                    body+="\nh2. Tutorials (Learning-Oriented)\n\n"
                    body+="Step-by-step lessons to get started.\n\n" ;;
                "How-to guides")
                    body+="\nh2. How-to Guides (Task-Oriented)\n\n"
                    body+="Practical guides for specific tasks.\n\n" ;;
                Reference)
                    body+="\nh2. Reference (Information-Oriented)\n\n"
                    body+="Technical reference material.\n\n" ;;
                "Architecture Decision Records")
                    body+="\nh2. Architecture Decision Records\n\n" ;;
                Templates)
                    body+="\nh2. Templates\n\n" ;;
            esac
            continue
        fi

        # Skip pure comments and blank lines
        [[ "$line" =~ ^#\  && ! "$line" =~ ^#\ --- ]] && [[ ! "$line" =~ \.md ]] && continue
        [[ -z "$line" ]] && continue

        # Parse doc entry: filename.md  # [X] Description
        local entry desc
        entry=$(echo "$line" | sed 's/#.*//; s/^[[:space:]]*//; s/[[:space:]]*$//')
        [[ -z "$entry" ]] && continue
        desc=$(echo "$line" | sed -n 's/.*# *\[.\] *//p')
        [[ -z "$desc" ]] && desc="$entry"

        # Build page title (same logic as upload_page — hyphens to spaces in basename only)
        local page_basename
        page_basename=$(basename "$entry" .md)
        page_basename=$(echo "$page_basename" | sed 's/-/ /g; s/  */ /g')
        local page_title="${CONFLUENCE_PREFIX}${page_basename}"

        body+="* [${desc}|${page_title}]\n"
    done < "$MANIFEST_FILE"

    body+="\n----\n\n"
    body+="{children:sort=title|excerpt=simple}"

    echo "$body"
}

# --- Create parent page under space home ---
create_parent_page() {
    local title="$1"
    local home_id="$2"
    local index_body
    index_body=$(build_index_body)

    local payload
    payload=$(cat <<ENDJSON
{
    "type": "page",
    "title": "${title}",
    "space": {"key": "${CONFLUENCE_SPACE_KEY}"},
    "ancestors": [{"id": "${home_id}"}],
    "body": {
        "wiki": {
            "value": "${index_body}",
            "representation": "wiki"
        }
    },
    "metadata": {
        "labels": [{"name": "${CONFLUENCE_LABEL}", "prefix": "global"}]
    }
}
ENDJSON
)
    local response
    response=$(curl "${CURL_OPTS[@]}" "${AUTH_ARGS[@]}" -w "\n%{http_code}" \
        -X POST \
        -H "Content-Type: application/json" \
        -d "$payload" \
        "${API_BASE}" 2>/dev/null) || true

    local http_code
    http_code=$(echo "$response" | tail -1)
    if [[ "$http_code" == "200" ]]; then
        local page_id=""
        if [[ "$HAS_JQ" == "true" ]]; then
            page_id=$(echo "$response" | head -1 | jq -r '.id // empty' 2>/dev/null)
        else
            page_id=$(echo "$response" | head -1 | grep -o '"id":"[0-9]*"' | head -1 | grep -o '[0-9]*')
        fi
        echo "$page_id"
    else
        echo ""
    fi
}

# --- Ensure parent page exists (auto-create if needed) ---
ensure_parent_page() {
    # If CONFLUENCE_PARENT_ID is already set, use it
    if [[ -n "$CONFLUENCE_PARENT_ID" ]]; then
        echo "Using provided parent page ID: ${CONFLUENCE_PARENT_ID}"
        return 0
    fi

    if [[ "$CONFLUENCE_DRY_RUN" == "true" ]]; then
        echo "[DRY RUN] Would auto-create parent page: '${CONFLUENCE_PARENT_TITLE}' under space home"
        echo ""
        echo "  Parent page index would contain:"
        build_index_body | sed 's/\\n/\n/g' | grep '^\*' | sed 's/^/    /'
        CONFLUENCE_PARENT_ID="DRY_RUN_PARENT"
        return 0
    fi

    # Check if parent page already exists
    echo -n "Looking for existing parent page '${CONFLUENCE_PARENT_TITLE}'... "
    local existing_id
    existing_id=$(find_page_id "$CONFLUENCE_PARENT_TITLE" 2>/dev/null) || true

    if [[ -n "$existing_id" ]]; then
        echo "found (id=${existing_id})"
        CONFLUENCE_PARENT_ID="$existing_id"
        # Update the index body on existing parent page
        echo -n "Updating parent page index... "
        local index_body
        index_body=$(build_index_body)
        local version
        version=$(get_page_version "$existing_id" 2>/dev/null) || version=0
        local new_version=$((version + 1))
        local update_payload
        update_payload=$(cat <<ENDJSON
{
    "id": "${existing_id}",
    "type": "page",
    "title": "${CONFLUENCE_PARENT_TITLE}",
    "space": {"key": "${CONFLUENCE_SPACE_KEY}"},
    "version": {"number": ${new_version}},
    "body": {
        "wiki": {
            "value": "${index_body}",
            "representation": "wiki"
        }
    }
}
ENDJSON
)
        local update_response
        update_response=$(curl "${CURL_OPTS[@]}" "${AUTH_ARGS[@]}" -w "\n%{http_code}" \
            -X PUT \
            -H "Content-Type: application/json" \
            -d "$update_payload" \
            "${API_BASE}/${existing_id}" 2>/dev/null) || true
        local update_code
        update_code=$(echo "$update_response" | tail -1)
        if [[ "$update_code" == "200" ]]; then
            echo "OK (v${new_version})"
        else
            echo "FAILED (HTTP ${update_code})"
        fi
        return 0
    fi
    echo "not found"

    # Get space home page ID
    echo -n "Getting space home page... "
    local home_id
    home_id=$(get_space_home_page_id 2>/dev/null) || true

    if [[ -z "$home_id" ]]; then
        echo "FAILED"
        echo "Could not find space home page. Set CONFLUENCE_PARENT_ID manually." >&2
        exit 1
    fi
    echo "OK (id=${home_id})"

    # Create parent page under home (NOT replacing home)
    echo -n "Creating parent page '${CONFLUENCE_PARENT_TITLE}' under space home... "
    local parent_id
    parent_id=$(create_parent_page "$CONFLUENCE_PARENT_TITLE" "$home_id")

    if [[ -z "$parent_id" ]]; then
        echo "FAILED"
        echo "Could not create parent page. Check permissions." >&2
        exit 1
    fi
    echo "OK (id=${parent_id})"
    CONFLUENCE_PARENT_ID="$parent_id"
}

# --- Upload attachments (mermaid PNGs) to a page ---
upload_attachments() {
    local page_id="$1"
    local basename="$2"

    for png in "${EXPORT_DIR}/${basename}"-mermaid-*.png; do
        [[ -f "$png" ]] || continue
        local png_name
        png_name=$(basename "$png")

        if [[ "$CONFLUENCE_DRY_RUN" == "true" ]]; then
            echo "    [DRY RUN] Would ATTACH: ${png_name}"
            continue
        fi

        # Check if attachment already exists on the page
        local existing_att_id=""
        local att_response
        att_response=$(curl "${CURL_OPTS[@]}" "${AUTH_ARGS[@]}" \
            "${API_BASE}/${page_id}/child/attachment?filename=${png_name}" 2>/dev/null) || true
        if [[ "$HAS_JQ" == "true" ]]; then
            existing_att_id=$(echo "$att_response" | jq -r '.results[0].id // empty' 2>/dev/null)
        fi

        local response http_code
        if [[ -n "$existing_att_id" ]]; then
            # Update existing attachment
            response=$(curl "${CURL_OPTS[@]}" "${AUTH_ARGS[@]}" -w "\n%{http_code}" \
                -X POST \
                -H "X-Atlassian-Token: nocheck" \
                -F "file=@${png}" \
                -F "minorEdit=true" \
                "${API_BASE}/${page_id}/child/attachment/${existing_att_id}/data" 2>/dev/null) || true
        else
            # Create new attachment
            response=$(curl "${CURL_OPTS[@]}" "${AUTH_ARGS[@]}" -w "\n%{http_code}" \
                -X POST \
                -H "X-Atlassian-Token: nocheck" \
                -F "file=@${png}" \
                -F "minorEdit=true" \
                "${API_BASE}/${page_id}/child/attachment" 2>/dev/null) || true
        fi

        http_code=$(echo "$response" | tail -1)
        if [[ "$http_code" == "200" ]]; then
            echo "    ATTACHED: ${png_name}"
        else
            echo "    ATTACH FAILED: ${png_name} (HTTP ${http_code})" >&2
            if [[ "$HAS_JQ" == "true" ]]; then
                echo "$response" | head -1 | jq -r '.message // empty' 2>/dev/null | sed 's/^/               /' >&2
            fi
        fi
    done
}

# --- Upload or update a single page ---
upload_page() {
    local file="$1"
    local basename
    basename=$(basename "$file" .confluence.txt)

    # Derive title from filename
    # Clean up basename: replace hyphens with spaces, collapse multiple spaces
    local clean_name
    clean_name=$(echo "$basename" | sed 's/-/ /g; s/  */ /g')
    local title="${CONFLUENCE_PREFIX}${clean_name}"

    local wiki_body
    wiki_body=$(cat "$file" | json_escape)

    # Build JSON payload — always nest under parent page
    local ancestors=""
    if [[ -n "$CONFLUENCE_PARENT_ID" && "$CONFLUENCE_PARENT_ID" != "DRY_RUN_PARENT" ]]; then
        ancestors='"ancestors": [{"id": "'"${CONFLUENCE_PARENT_ID}"'"}],'
    fi

    # Check if page already exists
    local existing_id
    existing_id=$(find_page_id "$title" 2>/dev/null) || true

    if [[ -n "$existing_id" ]]; then
        # Update existing page
        local version
        version=$(get_page_version "$existing_id" 2>/dev/null) || version=0
        local new_version=$((version + 1))

        if [[ "$CONFLUENCE_DRY_RUN" == "true" ]]; then
            echo "  [DRY RUN] Would UPDATE: ${title} (id=${existing_id}, v${version} → v${new_version})"
            upload_attachments "$existing_id" "$basename"
            return 0
        fi

        local payload
        payload=$(cat <<ENDJSON
{
    "id": "${existing_id}",
    "type": "page",
    "title": "${title}",
    "space": {"key": "${CONFLUENCE_SPACE_KEY}"},
    ${ancestors}
    "version": {"number": ${new_version}},
    "body": {
        "wiki": {
            "value": ${wiki_body},
            "representation": "wiki"
        }
    },
    "metadata": {
        "labels": [{"name": "${CONFLUENCE_LABEL}", "prefix": "global"}]
    }
}
ENDJSON
)
        local response
        response=$(curl "${CURL_OPTS[@]}" "${AUTH_ARGS[@]}" -w "\n%{http_code}" \
            -X PUT \
            -H "Content-Type: application/json" \
            -d "$payload" \
            "${API_BASE}/${existing_id}" 2>/dev/null) || true

        local http_code
        http_code=$(echo "$response" | tail -1)
        if [[ "$http_code" == "200" ]]; then
            echo "  UPDATED: ${title} (id=${existing_id}, v${new_version})"
            upload_attachments "$existing_id" "$basename"
        else
            echo "  FAILED:  ${title} (HTTP ${http_code})" >&2
            if [[ "$HAS_JQ" == "true" ]]; then
                echo "$response" | head -1 | jq -r '.message // empty' 2>/dev/null | sed 's/^/           /' >&2
            fi
            return 1
        fi
    else
        # Create new page
        if [[ "$CONFLUENCE_DRY_RUN" == "true" ]]; then
            echo "  [DRY RUN] Would CREATE: ${title}"
            upload_attachments "DRY_RUN" "$basename"
            return 0
        fi

        local payload
        payload=$(cat <<ENDJSON
{
    "type": "page",
    "title": "${title}",
    "space": {"key": "${CONFLUENCE_SPACE_KEY}"},
    ${ancestors}
    "body": {
        "wiki": {
            "value": ${wiki_body},
            "representation": "wiki"
        }
    },
    "metadata": {
        "labels": [{"name": "${CONFLUENCE_LABEL}", "prefix": "global"}]
    }
}
ENDJSON
)
        local response
        response=$(curl "${CURL_OPTS[@]}" "${AUTH_ARGS[@]}" -w "\n%{http_code}" \
            -X POST \
            -H "Content-Type: application/json" \
            -d "$payload" \
            "${API_BASE}" 2>/dev/null) || true

        local http_code
        http_code=$(echo "$response" | tail -1)
        if [[ "$http_code" == "200" ]]; then
            local page_id=""
            if [[ "$HAS_JQ" == "true" ]]; then
                page_id=$(echo "$response" | head -1 | jq -r '.id // empty' 2>/dev/null)
            fi
            echo "  CREATED: ${title}${page_id:+ (id=${page_id})}"
            if [[ -n "$page_id" ]]; then
                upload_attachments "$page_id" "$basename"
            fi
        else
            # If create failed because page already exists, retry as update
            local error_msg=""
            if [[ "$HAS_JQ" == "true" ]]; then
                error_msg=$(echo "$response" | head -1 | jq -r '.message // empty' 2>/dev/null)
            fi
            if echo "$error_msg" | grep -qi "title already exists"; then
                echo "  Page exists but wasn't found by search — retrying as update..."
                local retry_id
                retry_id=$(find_page_id "$title" 2>/dev/null) || true
                if [[ -z "$retry_id" ]]; then
                    # Search by title without prefix as last resort
                    echo "  FAILED:  ${title} — page exists but cannot be found by API search" >&2
                    echo "           Delete the existing page in Confluence or rename it, then retry." >&2
                    return 1
                fi
                local version
                version=$(get_page_version "$retry_id" 2>/dev/null) || version=0
                local new_version=$((version + 1))
                local update_payload
                update_payload=$(cat <<ENDJSON
{
    "id": "${retry_id}",
    "type": "page",
    "title": "${title}",
    "space": {"key": "${CONFLUENCE_SPACE_KEY}"},
    ${ancestors}
    "version": {"number": ${new_version}},
    "body": {
        "wiki": {
            "value": ${wiki_body},
            "representation": "wiki"
        }
    },
    "metadata": {
        "labels": [{"name": "${CONFLUENCE_LABEL}", "prefix": "global"}]
    }
}
ENDJSON
)
                local retry_response
                retry_response=$(curl "${CURL_OPTS[@]}" "${AUTH_ARGS[@]}" -w "\n%{http_code}" \
                    -X PUT \
                    -H "Content-Type: application/json" \
                    -d "$update_payload" \
                    "${API_BASE}/${retry_id}" 2>/dev/null) || true
                local retry_code
                retry_code=$(echo "$retry_response" | tail -1)
                if [[ "$retry_code" == "200" ]]; then
                    echo "  UPDATED: ${title} (id=${retry_id}, v${new_version}) [retry]"
                    upload_attachments "$retry_id" "$basename"
                else
                    echo "  FAILED:  ${title} (HTTP ${retry_code} on retry)" >&2
                    return 1
                fi
            else
                echo "  FAILED:  ${title} (HTTP ${http_code})" >&2
                if [[ -n "$error_msg" ]]; then
                    echo "           ${error_msg}" >&2
                fi
                return 1
            fi
        fi
    fi
}

# --- Build file list ---
build_file_list() {
    if [[ -n "$SINGLE_FILE" ]]; then
        echo "$SINGLE_FILE"
    elif [[ "$ARGS_ENTERPRISE" == "true" ]]; then
        # Enterprise mode: only files from the manifest
        if [[ ! -f "$MANIFEST_FILE" ]]; then
            echo "Error: Manifest not found: ${MANIFEST_FILE}" >&2
            echo "Expected docs/confluence-manifest.txt with list of enterprise docs." >&2
            exit 1
        fi
        while IFS= read -r line; do
            entry=$(echo "$line" | sed 's/#.*//; s/^[[:space:]]*//; s/[[:space:]]*$//')
            [[ -z "$entry" ]] && continue
            # Convert manifest entry to .confluence.txt filename
            local_base=$(basename "$entry" .md)
            filepath="${EXPORT_DIR}/${local_base}.confluence.txt"
            if [[ -f "$filepath" ]]; then
                echo "$filepath"
            else
                echo "  WARNING: ${local_base}.confluence.txt not found — run export-to-confluence.sh --enterprise first" >&2
            fi
        done < "$MANIFEST_FILE"
    else
        find "${EXPORT_DIR}" -name '*.confluence.txt' -type f | sort
    fi
}

# --- Main ---
echo "Uploading to Confluence..."
echo ""

# Ensure parent page exists (auto-create under space home, never overwrites home)
ensure_parent_page
echo ""

success=0
failed=0
total=0

while IFS= read -r f; do
    [[ -z "$f" ]] && continue
    total=$((total + 1))
    if upload_page "$f"; then
        success=$((success + 1))
    else
        failed=$((failed + 1))
    fi
done < <(build_file_list)

echo ""
echo "Done. ${success} uploaded, ${failed} failed (${total} total)."

if [[ "$CONFLUENCE_DRY_RUN" == "true" ]]; then
    echo ""
    echo "This was a dry run. Add --confirm to upload for real:"
    echo "  bash scripts/upload-to-confluence.sh --enterprise --confirm"
fi

echo ""
echo "---"
echo "Example .env.confluence file:"
echo ""
echo "  # Confluence Server/DC 9.x (PAT auth — recommended)"
echo "  CONFLUENCE_URL=https://wiki.company.com"
echo "  CONFLUENCE_SPACE_KEY=PYRO"
echo "  CONFLUENCE_TOKEN=your-personal-access-token"
echo "  # CONFLUENCE_AUTH_TYPE=pat                # default"
echo "  # CONFLUENCE_PARENT_TITLE=Pyroscope Documentation  # auto-created"
echo "  # CONFLUENCE_PREFIX=\"Pyroscope - \""
echo "  # CONFLUENCE_LABEL=pyroscope-docs"
echo "  # CONFLUENCE_VERIFY_SSL=false             # for self-signed certs"
echo ""
echo "  # Confluence Cloud (basic auth)"
echo "  # CONFLUENCE_AUTH_TYPE=basic"
echo "  # CONFLUENCE_USER=john.doe@company.com"
echo "  # CONFLUENCE_TOKEN=your-api-token"
