apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pyroscope-data
  namespace: pyroscope
  labels:
    app.kubernetes.io/name: pyroscope
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
