apiVersion: 1

datasources:
  - name: Pyroscope
    type: grafana-pyroscope-datasource
    uid: pyroscope-ds
    access: proxy
    url: http://pyroscope:4040    # Replaced at deploy time with actual Pyroscope URL
    editable: true
